name: Publish to Luarocks

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  luarocks-upload:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          test_interpreters: ""
          dependencies: |
            luarocks-build-rust-binary
          labels: |
            rust
            norgopolis
            neorg
          detailed_description:
            The Norgopolis server module automatically compiles and exposes a norgopolis-server binary
            which may be invoked from any program using the module as a dependency.

            The module exposes a function that returns the path to the installed binary.
